### ISSUE TITLE
[feat] 대표 전략 통합 평균 지표 CSS

### ISSUE THREAD

**Issue by seoyoonyi** [FC-DEV-FinalProject/FinalProject_2VEN_FE#47]
### 📄 설명

대표 전략 통합 평균 지표 CSS

### ✅ 해야 할 일

- [x] 그래프와 관련된 색상, 레이블 스타일, 축 설정 및 레이아웃 조정 작업
- [x] API 작업 없이 이미지로만 구성됩니다.

### 📝 메모

<img width="895" alt="스크린샷 2024-11-13 오전 11 31 14" src="https://github.com/user-attachments/assets/91ab51f4-932b-4c53-a8e8-5975c0f5b0bb">

**Comment by Panda-raccoon** [comment]
어려워요..
